name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # PHP setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, bcmath, json, sqlite
          ini-values: post_max_size=256M, max_execution_time=180

      # Composer install
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # Create .env.testing
      - name: Create testing env
        run: cp .env.example .env.testing

      # Generate key & migrate
      - name: Prepare application
        env:
          APP_ENV: testing
        run: |
          php artisan key:generate --ansi
          php artisan migrate --env=testing --force

      # Run Pint (code style)
      - name: Check code style with Pint
        run: vendor/bin/pint -- --check

      # Run PHPStan (static analysis)
      - name: Static analysis with PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G

      # Run PHPUnit
      - name: Run tests
        run: vendor/bin/phpunit --fail-on-warning --verbose
