# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código
      - uses: actions/checkout@v3

      # 2. Configura PHP e extensões necessárias
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, json, sqlite
          ini-values: post_max_size=256M, max_execution_time=180

      # 3. Instala dependências via Composer
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # 4. Prepara ambiente de teste
      - name: Prepare test environment
        run: |
          cp .env.example .env.testing
          php artisan key:generate --ansi --env=testing
